-- AlterTable
ALTER TABLE "SmsProvider"
ADD COLUMN "type" TEXT NOT NULL DEFAULT 'smtp',
ADD COLUMN "targetRatePerSecond" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN "maxRatePerSecond" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "warmupEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "warmupStartRps" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD COLUMN "warmupIncrementStep" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD COLUMN "warmupMaxRps" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN "dailyCap" INTEGER,
ADD COLUMN "hourlyCap" INTEGER,
ADD COLUMN "minuteCap" INTEGER,
ADD COLUMN "isThrottled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "throttleReason" TEXT,
ADD COLUMN "cooldownUntil" TIMESTAMP(3),
ADD COLUMN "lastError" TEXT,
ADD COLUMN "healthStatus" TEXT NOT NULL DEFAULT 'healthy',
ADD COLUMN "deletedAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "SmsProvider_deletedAt_isActive_idx" ON "SmsProvider"("deletedAt", "isActive");
